# S3_BUCKET_NAME: tylor-lambda-dashboard
# S3_DEST_PREFIX: lambda
# DYNAMO_DB_TABLE_NAME: lambda-image-manager-stats
# MAX_SIZE_LIMIT: 2000000
S3_BUCKET_NAME: my-site-images-test
S3_DEST_PREFIX: lambda
DYNAMO_DB_TABLE_NAME: lambda-image-manager-stats
MAX_SIZE_LIMIT: 2000000
